// Converts videos/VIDEO/screens/*.ans (tmux capture-pane -e) into
// videos/VIDEO/screens.js:  node lib/ansi2json.mjs VIDEO
//   window.SCREENS[name] = { skin, rows: [[ [text, fg, bg, flags], ... ], ...] }
//   window.SKINS[name]   = { bg, text } from skins.json (see below)
//   window.SEQS[name]    = [[seconds, frameName], ...] for `anim` recordings
// A screen's skin comes from NAME.meta (skin=...), else a skin_X in its name,
// else $SKIN, else "default".
//
// skins.json (next to package.json, optional) maps each theme name you record
// with to the terminal's default colours for it, which the app never paints
// itself: { "default": { "bg": "#1e1e1e", "text": "#d4d4d4" }, ... }
// flags: 1 bold, 2 faint, 4 italic, 8 underline. fg/bg null = terminal default.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const video = path.resolve(here, '..');
const skinsFile = path.join(video, 'skins.json');
const skins = fs.existsSync(skinsFile) ? JSON.parse(fs.readFileSync(skinsFile, 'utf8')) : {};
skins.default ||= { bg: '#1e1e1e', text: '#d4d4d4' };

const ansi16 = ['#15161e', '#f7768e', '#9ece6a', '#e0af68', '#7aa2f7', '#bb9af7', '#7dcfff', '#a9b1d6',
  '#414868', '#f7768e', '#9ece6a', '#e0af68', '#7aa2f7', '#bb9af7', '#7dcfff', '#c0caf5'];
const hex = (r, g, b) => '#' + [r, g, b].map((v) => (+v).toString(16).padStart(2, '0')).join('');
function xterm256(n) {
  if (n < 16) return ansi16[n];
  if (n < 232) { n -= 16; const c = [0, 95, 135, 175, 215, 255]; return hex(c[Math.floor(n / 36)], c[Math.floor(n / 6) % 6], c[n % 6]); }
  const v = 8 + (n - 232) * 10; return hex(v, v, v);
}

function parse(src) {
  let fg = null, bg = null, fl = 0;
  const rows = [];
  for (const line of src.replace(/\n$/, '').split('\n')) {
    const runs = [];
    let buf = '';
    const flush = () => {
      if (!buf) return;
      const last = runs[runs.length - 1];
      if (last && last[1] === fg && last[2] === bg && last[3] === fl) last[0] += buf;
      else runs.push([buf, fg, bg, fl]);
      buf = '';
    };
    const re = /\x1b\[([0-9;]*)m|([^\x1b]+)/g;
    let m;
    while ((m = re.exec(line))) {
      if (m[2] !== undefined) { buf += m[2]; continue; }
      flush();
      const a = (m[1] || '0').split(';').map(Number);
      for (let i = 0; i < a.length; i++) {
        const c = a[i];
        if (c === 0) { fg = bg = null; fl = 0; }
        else if (c === 1) fl |= 1; else if (c === 2) fl |= 2; else if (c === 3) fl |= 4; else if (c === 4) fl |= 8;
        else if (c === 22) fl &= ~3; else if (c === 23) fl &= ~4; else if (c === 24) fl &= ~8;
        else if (c === 39) fg = null; else if (c === 49) bg = null;
        else if (c === 38 || c === 48) {
          let col;
          if (a[i + 1] === 2) { col = hex(a[i + 2], a[i + 3], a[i + 4]); i += 4; }
          else { col = xterm256(a[i + 2]); i += 2; }
          if (c === 38) fg = col; else bg = col;
        }
        else if (c >= 30 && c <= 37) fg = ansi16[c - 30]; else if (c >= 90 && c <= 97) fg = ansi16[c - 82];
        else if (c >= 40 && c <= 47) bg = ansi16[c - 40]; else if (c >= 100 && c <= 107) bg = ansi16[c - 92];
      }
    }
    flush();
    rows.push(runs);
  }
  return rows;
}

const name0 = process.argv[2];
if (!name0) { console.error('usage: node lib/ansi2json.mjs VIDEO'); process.exit(1); }
const vdir = path.join(video, 'videos', name0);
const dir = path.join(vdir, 'screens');
const screens = {}, seqs = {};
for (const f of fs.readdirSync(dir).sort()) {
  const full = path.join(dir, f);
  if (f.endsWith('.seq')) {
    seqs[f.slice(0, -4)] = fs.readFileSync(full, 'utf8').trim().split('\n').map((l) => { const [t, fr] = l.split(' '); return [+t, fr]; });
    continue;
  }
  if (!f.endsWith('.ans')) continue;
  const name = f.slice(0, -4);
  const meta = path.join(dir, name + '.meta');
  const fromMeta = fs.existsSync(meta) ? (fs.readFileSync(meta, 'utf8').match(/skin=(\S+)/) || [])[1] : null;
  const skin = fromMeta || (name.match(/(?:^|_)skin_(.+)$/) || [])[1] || process.env.SKIN || 'default';
  if (!skins[skin]) { console.warn(`${name}: no colours for skin "${skin}" in skins.json, using default`); }
  screens[name] = { skin: skins[skin] ? skin : 'default', rows: parse(fs.readFileSync(full, 'utf8')) };
}
const out = path.join(vdir, 'screens.js');
fs.writeFileSync(out, '// Generated by lib/ansi2json.mjs from screens/. Do not edit.\n' +
  'window.SKINS = ' + JSON.stringify(skins) + ';\n' +
  'window.SCREENS = ' + JSON.stringify(screens) + ';\n' +
  'window.SEQS = ' + JSON.stringify(seqs) + ';\n');
console.log(`wrote ${path.relative(video, out)}: ${Object.keys(screens).length} screens, ${Object.keys(skins).length} skins`);
