#!/usr/bin/env python3
"""Deterministic generator for internal/argo/testdata fixtures.

Fixture policy: every fixture here is explicitly
SYNTHETIC and generated by this script — never a captured production
payload. Regenerate with:  python3 testdata/gen_fixtures.py
"""
import os

TD = os.path.dirname(os.path.abspath(__file__))


def w(name: str, data: bytes) -> None:
    with open(os.path.join(TD, name), "wb") as f:
        f.write(data)


# List page 1: two summaries, continuation token "100" (v4.1.2 emits
# integer-string offsets, but the client must treat them as opaque —
# live resourceVersion.
w("list_page1.json", b"""{
  "metadata": {"continue": "100", "resourceVersion": "rv-live-1"},
  "items": [
    {
      "metadata": {
        "name": "train-pipeline",
        "namespace": "team-a",
        "uid": "uid-1",
        "resourceVersion": "11",
        "labels": {"workflows.argoproj.io/phase": "Running"},
        "creationTimestamp": "2026-09-08T10:00:00Z"
      },
      "status": {
        "phase": "Running",
        "message": "running",
        "startedAt": "2026-09-08T10:01:00Z"
      }
    },
    {
      "metadata": {
        "name": "nightly-report",
        "namespace": "team-a",
        "uid": "uid-2",
        "resourceVersion": "12",
        "creationTimestamp": "2026-09-08T09:00:00Z"
      },
      "status": {
        "phase": "WaitingForDependency",
        "finishedAt": "2026-09-08T09:37:00Z"
      }
    }
  ]
}
""")

# List page 2: zero items with a terminating (empty) continuation. The
# caller must follow continuation even when a page contains zero items.
w("list_page2.json", b"""{
  "metadata": {"continue": "", "resourceVersion": "rv-live-2"},
  "items": []
}
""")

# Hydrated detail: DAG nodes with children/outboundNodes/boundaryID, a
# reference to a node id absent from the map (explicit missing data), and
# unknown fields (spec templates + a custom extension) that must survive
# verbatim in Workflow.Resource.
w("workflow_detail.json", b"""{
  "metadata": {
    "name": "dag-complex",
    "namespace": "team-a",
    "uid": "wf-uid-111",
    "resourceVersion": "77",
    "labels": {"workflows.argoproj.io/phase": "Running"},
    "creationTimestamp": "2026-09-08T10:00:00Z"
  },
  "spec": {
    "entrypoint": "main",
    "templates": [{"name": "main", "dag": {"tasks": [{"name": "echo", "template": "echo"}]}}],
    "x-custom-extension": "preserve-me-42"
  },
  "status": {
    "phase": "Running",
    "message": "progress 1/2",
    "startedAt": "2026-09-08T10:00:05Z",
    "nodes": {
      "node-root": {
        "name": "dag-complex",
        "displayName": "dag-complex",
        "type": "DAG",
        "phase": "Running",
        "children": ["node-echo"],
        "outboundNodes": ["node-echo"],
        "startedAt": "2026-09-08T10:00:05Z"
      },
      "node-echo": {
        "name": "dag-complex.echo",
        "displayName": "echo",
        "type": "Pod",
        "phase": "Succeeded",
        "boundaryID": "node-root",
        "startedAt": "2026-09-08T10:00:06Z",
        "finishedAt": "2026-09-08T10:00:09Z"
      },
      "node-suspend": {
        "name": "dag-complex.suspend",
        "displayName": "suspend",
        "type": "Suspend",
        "phase": "Running",
        "boundaryID": "node-root"
      },
      "node-ghost-parent": {
        "name": "dag-complex.gap",
        "displayName": "gap",
        "type": "Steps",
        "phase": "Pending",
        "children": ["node-missing-id"]
      }
    }
  }
}
""")

# Offloaded (unhydrated) detail: markers prove node data exists but is not
# hydrated — must map to NodesAvailable=false + reason, never an empty
# workflow.
w("workflow_offloaded.json", b"""{
  "metadata": {
    "name": "big-hydrate",
    "namespace": "team-a",
    "uid": "wf-uid-222",
    "resourceVersion": "90",
    "creationTimestamp": "2026-09-08T08:00:00Z"
  },
  "status": {
    "phase": "Succeeded",
    "compressedNodes": "H4sIAAAAAAAA-w",
    "offloadNodeStatusVersion": "v1"
  }
}
""")

# Log stream, bare JSON-lines framing (gateway v1.16.0 source behavior,
# Last line deliberately has NO trailing newline.
# Line 3 contains a raw invalid UTF-8 byte (0xFF) inside the content
# string — Go's JSON decoder replaces it with U+FFFD.
w("logs_jsonl.txt",
  b'{"result":{"content":"line-one","podName":"pod-a"}}\n'
  b'{"result":{"content":"line-two","podName":"pod-b"}}\n'
  b'{"result":{"content":"line-\xffbad","podName":"pod-b"}}\n'
  b'{"result":{"content":"final-no-newline","podName":"pod-c"}}')

# Same records, SSE framing (Argo's own HTTP1 client + e2e expectations,
# "data: " prefixes, keepalive comment, blank-line
# event separation, EOF dispatches the pending event.
w("logs_sse.txt",
  b': keepalive\n'
  b'\n'
  b'data: {"result":{"content":"line-one","podName":"pod-a"}}\n'
  b'\n'
  b'data: {"result":{"content":"line-two","podName":"pod-b"}}\n'
  b'\n'
  b'data: {"result":{"content":"line-\xffbad","podName":"pod-b"}}\n'
  b'\n'
  b'data: {"result":{"content":"final-no-newline","podName":"pod-c"}}')

# Dedicated unknown-phase fixture: a phase string outside the pinned
# v4.1.1 enum must decode verbatim and stay displayable, never error.
w("list_unknown_phase.json", b"""{
  "metadata": {"continue": "", "resourceVersion": "rv-unknown"},
  "items": [
    {
      "metadata": {
        "name": "weird-one",
        "namespace": "ns-x",
        "uid": "uid-9",
        "resourceVersion": "5",
        "creationTimestamp": "2026-09-08T11:00:00Z"
      },
      "status": {
        "phase": "ZombifiedByUpgrade",
        "message": "phase introduced by a newer controller"
      }
    }
  ]
}
""")

print("fixtures written to", TD)
